Repository HackYourFuture-CPH/fp-class19, pull requests merged in 2022-03, with the labels that each got.

#105 Frontend: Order Confirm Component
  src/client/App.js
  src/client/containers/OrderConfirmationPage/OrderConfirmationPage.Container.js
  src/client/containers/OrderConfirmationPage/OrderConfirmationPage.styles.css
Labels: Frontend

#192 Get product by id: response status codes fixed
  src/server/api/controllers/products.controller.js
Labels: Backend

#196 End-point: api/products/on_discount updated with error codes
  src/server/api/controllers/products.controller.js
  src/server/api/routes/products.router.js
Labels: Backend

#144 BackEnd: Feature/new order
  src/server/api/controllers/orders.controller.js
  src/server/api/routes/api-router.js
  src/server/api/routes/orders.router.js
Labels: Backend

#162 Modal
  src/client/assets/images/added_to_cart.png
  src/client/components/Modal/Modal.component.js
  src/client/components/Modal/Modal.stories.js
  src/client/components/Modal/Modal.styles.css
  src/client/containers/LandingPage/LandingPage.container.js
Labels: Storybook, Frontend

#223 Frontend: Product preview
  src/client/components/ProductPreview/ProductPreview.component.js
  src/client/components/ProductPreview/ProductPreview.stories.js
  src/client/components/ProductPreview/ProductPreview.styles.css
Labels: Storybook, Frontend

#199 Backend : Update endpoint /api/favorites/add with error handlers
  src/server/api/controllers/favorites.controller.js
  src/server/api/routes/favorites.router.js
Labels: Backend, Low

#210 Endpoint: fixed user's favorite list details
  src/server/api/controllers/users.controller.js
Labels: Backend, Medium

#218 Browser icon and title updated
  public/favicon.ico
  public/index.html
Labels: Frontend, Low

#227 Frontend: Fix ProductPreview Component #226
  src/client/components/ProductPreview/ProductPreview.component.js
  src/client/components/ProductPreview/ProductPreview.styles.css
Labels: Frontend

#185 add/remove/modify products in shoppingcart
  src/client/App.js
  src/client/components/Header/Header.component.js
  src/client/components/Header/Header.styles.css
  src/client/components/OfferProductsList/OfferProductsList.component.js
  src/client/components/Product/Product.component.js
  src/client/components/Product/Product.styles.css
  src/client/components/Products/Products.component.js
  src/client/components/ProductsPageView/ProductsPageView.component.js
  src/client/components/ProductsView/ProductsView.component.js
  src/client/components/ShoppingCart/ModifyProductQuantity.js
  src/client/components/ShoppingCart/RemoveFromShoppingCart.js
  src/client/components/ShoppingCart/ShoppingCart.component.js
  src/client/components/ShoppingCart/ShoppingCart.styles.css
  src/client/components/ShoppingCart/ShoppingCartImage.js
  src/client/components/SpecialOfferBanner/SpecialOfferBanner.component.js
  src/client/components/SpecialOffers/OfferProductModel.component.js
  src/client/components/SpecialOffers/OfferProductModel.styles.css
  src/client/containers/Home/Home.test.js
  src/client/containers/ShoppingCartPage/ShoppingCartPage.Container.js
  src/client/containers/ShoppingCartPage/ShoppingCartPage.styles.css
  src/client/containers/SpecialOfferPage/SpecialOfferPage.container.js
Labels: Frontend, High, Urgent

#220 Frontend: create account page
  src/client/App.js
  src/client/assets/images/image_15.png
  src/client/components/CreateAccountForm/CreateAccountForm.component.js
  src/client/components/CreateAccountForm/CreateAccountForm.styles.css
  src/client/components/Footer/Footer.styles.css
  src/client/components/Forms/CreateAccountForm/CreateAccountForm.component.js
  src/client/components/Header/Header.styles.css
  src/client/containers/CreateAccountPage/CreateAccountPage.Container.js
  src/client/containers/CreateAccountPage/CreateAccountPage.container.js
  src/client/containers/CreateAccountPage/CreateAccountPage.styles.css
Labels: Frontend, Low

#141 feat: firebase login integration
  src/client/App.js
  src/client/components/Auth/AuthenticatedRoute.js
  src/client/components/CreateAccountForm/CreateAccountForm.component.js
  src/client/components/FavouriteList/FavouriteList.component.js
  src/client/components/FavouriteList/FavouriteList.styles.css
  src/client/components/FavouriteList/ProductImage.js
  src/client/components/Header/Header.component.js
  src/client/components/Login/Login.component.js
  src/client/components/Login/Login.styles.css
  src/client/components/Pagination/Pagination.stories.js
  src/client/components/Success/UserCreationSuccess.js
  src/client/components/UserProfile/UserProfile.component.js
  src/client/components/UserProfile/UserProfile.styles.css
  src/client/containers/CreateAccountPage/CreateAccountPage.container.js
  src/client/containers/FavoritePage/FavoritePage.Container.js
  src/client/containers/FavoritePage/FavoritePage.styles.css
  src/client/containers/FavouritePage/FavouritePage.Container.js
  src/client/containers/FavouritePage/FavouritePage.styles.css
  src/client/containers/Profile/index.js
  src/client/containers/UserProfilePage/UserProfilePage.Container.js
  src/client/firebase/FirebaseContext.js
  src/client/firebase/auth.js
  src/client/firebase/configure.js
  src/client/hooks/useAuthentication.js
  src/server/api/controllers/users.controller.js
  src/server/api/routes/users.router.js
  src/server/migrations/20220129153235_create_users_table.js
  src/server/migrations/20220202135116_create_favorites_table.js
  src/server/migrations/20220215204621_create_orders_table.js
  src/server/seeds/development/01_users_table.js
  src/server/seeds/development/03_orders_table.js
  src/server/seeds/development/05_favorites_table.js
Labels: Firebase, High, Urgent

#207 Update to endpoint to delete favorites(products) of a user with error handlers/responses
  src/server/api/controllers/favorites.controller.js
  src/server/api/routes/favorites.router.js
Labels: Backend, Medium

#217 Sort Component fix storybook
  src/client/components/Products/Products.component.js
  src/client/components/ProductsPageView/ProductsPageView.component.js
  src/client/components/SortComponent/Sorting.component.js
  src/client/components/SortComponent/Sorting.stories.js
  src/client/components/SortComponent/Sorting.styles.css
Labels: bug, Storybook, Low

#204 add/remove to favorites for a user
  src/client/App.js
  src/client/assets/images/heartFill.png
  src/client/components/FavoriteList/FavoriteList.component.js
  src/client/components/FavoriteList/FavoriteList.styles.css
  src/client/components/FavoriteList/FavoriteProductImage.js
  src/client/components/FavoriteList/FavoriteProductQuantitySelector.js
  src/client/components/FavoriteList/RemoveFromFavorites.js
  src/client/components/FavouriteList/FavouriteList.component.js
  src/client/components/FavouriteList/FavouriteList.stories.js
  src/client/components/FavouriteList/ProductCart.js
  src/client/components/FavouriteList/ProductImage.js
  src/client/components/Header/Header.component.js
  src/client/components/Header/Header.styles.css
  src/client/components/OfferProductsList/OfferProductsList.component.js
  src/client/components/Product/Product.component.js
  src/client/components/Product/Product.styles.css
  src/client/components/ProductsView/ProductsView.component.js
  src/client/components/SpecialOffers/OfferProductModel.component.js
  src/client/components/SpecialOffers/OfferProductModel.styles.css
  src/client/containers/FavoritePage/FavoritePage.Container.js
  src/client/containers/FavoritePage/FavoritePage.styles.css
  src/client/containers/LandingPage/LandingPage.container.js
  src/client/containers/SpecialOfferPage/SpecialOfferPage.container.js
  src/client/hooks/useAuthentication.js
  src/server/api/controllers/favorites.controller.js
  src/server/api/controllers/users.controller.js
  src/server/api/routes/favorites.router.js
  src/server/api/routes/users.router.js
Labels: Frontend, High, Urgent

#229 complete shopping cart page
  src/client/App.js
  src/client/components/ShoppingCart/ModifyProductQuantity.js
  src/client/components/ShoppingCart/RemoveFromShoppingCart.js
  src/client/components/ShoppingCart/ShoppingCart.component.js
  src/client/components/ShoppingCart/ShoppingCart.styles.css
  src/client/containers/ShoppingCartPage/ShoppingCartPage.Container.js
  src/client/containers/ShoppingCartPage/ShoppingCartPage.styles.css
Labels: Frontend, High

#230 Storybook: Shopping-cart & favorite header menu icon(showing how many items in there)
  src/client/App.js
  src/client/components/Header/Header.component.js
  src/client/components/Header/Header.stories.js
  src/client/components/Header/Header.styles.css
Labels: Storybook

#219 Paypal-Payment
  public/index.html
  src/client/.storybook/preview-head.html
  src/client/App.js
  src/client/components/Paypal/Paypal.component.js
  src/client/components/Paypal/Paypal.stories.js
  src/client/containers/Paypal/PaypalPage.container.js
  src/client/containers/Paypal/PaypalPage.css
Labels: Frontend, Low

#203 Database: Create Families table and its routers, controllers, migrations, seeds
  src/server/api/controllers/families.controller.js
  src/server/api/controllers/products.controller.js
  src/server/api/routes/api-router.js
  src/server/api/routes/families.router.js
  src/server/migrations/20220122070000_create_families_table.js
  src/server/migrations/20220123184131_create_products_table.js
  src/server/seeds/development/02_families_table.js
  src/server/seeds/development/03_products_table.js
  src/server/seeds/development/04_orders_table.js
  src/server/seeds/development/05_order_items_table.js
  src/server/seeds/development/06_favorites_table.js
Labels: Databases, Backend, Medium

#233 wrap fav button in header in link and button
  src/client/components/Header/Header.component.js
Labels: Frontend

#232 Frontend: Product Page
  src/client/App.js
  src/client/components/Carousel/Carousel.js
  src/client/components/Carousel/CarouselStyle.css
  src/client/components/ProductDetail/ProductDetail.component.js
  src/client/components/ProductDetail/ProductDetail.styles.css
  src/client/containers/ProductPage/ProductPage.Container.js
  src/client/containers/ProductPage/ProductPage.styles.css
Labels: Frontend

#237 Fix product links
  src/client/App.js
  src/client/components/FavoriteList/FavoriteProductImage.js
  src/client/components/Product/Product.component.js
  src/client/components/Product/Product.styles.css
  src/client/components/ProductDetail/ProductDetail.component.js
  src/client/components/ProductDetail/ProductDetail.styles.css
  src/client/components/ShoppingCart/ShoppingCart.component.js
  src/client/components/SpecialOffers/OfferProductModel.component.js
  src/client/components/SpecialOffers/OfferProductModel.styles.css
  src/client/containers/ProductPage/ProductPage.Container.js
Labels: Frontend

#235 Update header links profile and favorites
  src/client/components/Header/Header.component.js
  src/client/components/Header/Header.styles.css
  src/client/components/UserProfile/UserProfile.styles.css
Labels: Frontend

#241 Feature-shopping cart-PayPalpayment
  public/index.html
  src/client/.storybook/preview-head.html
  src/client/components/Paypal/Paypal.component.js
  src/client/components/Paypal/Paypal.stories.js
  src/client/components/ShoppingCart/ShoppingCart.component.js
  src/client/components/ShoppingCart/ShoppingCart.styles.css
Labels: Frontend, Backend
