Repository HackYourFuture-CPH/fp-class19, pull requests merged in 2022-02, with the labels that each got.

#50 Feature/product component
  src/client/assets/images/cart_bucket.png
  src/client/assets/images/heart.png
  src/client/assets/images/image_10.png
  src/client/assets/images/image_12.png
  src/client/assets/images/image_13.png
  src/client/assets/images/image_16.png
  src/client/assets/images/image_17.png
  src/client/assets/images/image_18.png
  src/client/assets/images/image_19.png
  src/client/assets/images/image_20.png
  src/client/assets/images/image_21.png
  src/client/assets/images/image_22.png
  src/client/assets/images/image_24.png
  src/client/assets/images/image_25.png
  src/client/assets/images/image_4.png
  src/client/assets/images/image_6.png
  src/client/assets/images/image_7.png
  src/client/components/Product/Product.js
  src/client/components/Product/Product.stories.js
  src/client/components/Product/Product.styles.css
Labels: Storybook

#58 update the Swagger instructions
  README.md
Labels: documentation

#39 Created Contact-us page content
  .env.example
  src/client/App.js
  src/client/assets/images/image26.png
  src/client/components/Footer/Footer.css
  src/client/components/contact-page/Contact.js
  src/client/components/contact-page/contact.css
Labels: Frontend

#37 Pagination component
  src/client/components/PaginationComponent/PaginationComponent.js
  src/client/components/PaginationComponent/PaginationComponent.stories.js
  src/client/components/PaginationComponent/PaginationComponent.styles.css
Labels: Frontend

#64 FrontEnd: Display of All Products Component Using Product Component and Sort Component
  src/client/components/Product/Product.js
  src/client/components/Product/Product.stories.js
  src/client/components/ProductsComponent/ProductsComponent.js
  src/client/components/ProductsComponent/ProductsComponent.stories.js
  src/client/components/ProductsComponent/ProductsComponent.styles.css
  src/client/components/SortComponent/SortComponent.js
Labels: Storybook, Frontend

#56 Frontend: Spinner #22
  src/client/App.js
  src/client/components/Loader/Loader.component.js
  src/client/components/Loader/index.js
  src/client/components/Loader/loader-component.css
  src/client/containers/ResetPassword/index.js
  src/client/containers/SignIn/index.js
  src/client/containers/SignUp/index.js
Labels: Frontend

#67 Frontend: Feature/fixing styles
  src/client/App.js
  src/client/assets/images/image_27.png
  src/client/assets/images/logo1.png
  src/client/components/AboutUs/aboutus.component.js
  src/client/components/Footer/Footer.css
  src/client/components/Footer/Footer.js
  src/client/components/Header/Header.css
  src/client/components/Header/Header.js
  src/client/components/LoginComponent/LoginComponent.js
  src/client/components/Menu/Menu.js
  src/client/components/Menu/menu.css
  src/client/components/SpecialOfferBanner/Specialoffer.css
  src/client/components/SpecialOfferBanner/Specialoffer.js
  src/client/index.css
Labels: Frontend

#72 FrontEnd: Display of All Products Component Using Product Component
  src/client/components/ProductsView/ProductsView.js
  src/client/components/ProductsView/ProductsView.stories.js
  src/client/components/ProductsView/ProductsView.styles.css
Labels: Storybook, Frontend

#63 Save new user data
  src/server/api/controllers/users.controller.js
  src/server/api/routes/api-router.js
  src/server/api/routes/users.router.js
Labels: Ready for development, Backend

#57 added favorite list images
  src/client/assets/images/image_29.png
  src/client/assets/images/image_30.png
  src/client/assets/images/image_31.png
Labels: Frontend

#81 Feature/spinner
  src/client/components/Loader/Loader.component.js
  src/client/components/Loader/LoaderComponent.stories.js
Labels: Storybook

#80 new-get-products-PR
  src/client/components/PaginationComponent/PaginationComponent.js
  src/client/components/PaginationComponent/PaginationComponent.stories.js
  src/server/api/controllers/products.controller.js
  src/server/api/routes/api-router.js
  src/server/api/routes/products.router.js
Labels: Backend

#93 Create additional query parameters for protucts api limit and offset
  src/server/api/controllers/products.controller.js
  src/server/api/routes/products.router.js
Labels: Backend

#91 Frontend-ContactPage-Container
  src/client/App.js
  src/client/components/Footer/Footer.js
  src/client/components/Header/Header.js
  src/client/containers/ContactUsPage/ContactUsPage.Container.js
Labels: Frontend

#86 Feature/product by
  src/server/api/controllers/products.controller.js
  src/server/api/routes/products.router.js
Labels: Backend

#87 Feature/discount products
  src/server/api/controllers/products.controller.js
  src/server/api/routes/products.router.js
Labels: Backend

#103 Feature/special offers
  src/client/assets/images/image_28.png
  src/client/components/SpecialOffers/Product.js
  src/client/components/SpecialOffers/Product.stories.js
  src/client/components/SpecialOffers/Product.styles.css
Labels: Storybook, Frontend

#98 Frontend-AboutUsPage-Container
  src/client/App.js
  src/client/components/AboutUs/aboutus.component.js
  src/client/components/Footer/Footer.css
  src/client/containers/AboutUsPage/AboutUsPage.Container.js
Labels: Frontend

#79 Get favourite endpoint
  README.md
  src/server/api/controllers/users.controller.js
  src/server/api/routes/users.router.js
Labels: Backend

#119 Bug: Build failing due to error in Header
  src/client/components/FavouriteList/ProductCart.js
  src/client/components/Header/Header.js
  src/client/components/Header/Header.stories.js
Labels: bug

#117 FrontEnd: Display of menu and footer on every Page you access
  src/client/App.js
  src/client/containers/AboutUsPage/AboutUsPage.Container.js
  src/client/containers/ContactUsPage/ContactUsPage.Container.js
Labels: Frontend

#134 Correcting the calendar days of the project
  README.md
Labels: documentation

#127 Backend : Adding image URLs into the DB
  src/server/seeds/development/01_products_table.js
Labels: Databases

#133 Frontend: Menu component fix #132
  src/client/components/Menu/Menu.component.js
Labels: Frontend

#129 Frontend: ESLint Warnings Fix #128
  src/client/components/FavouriteList/ProductCart.js
  src/client/components/FavouriteList/ProductImage.js
  src/client/components/FavouriteList/ProductQuantity.js
  src/client/components/Pagination/Pagination.stories.js
  src/client/components/Products/Products.component.js
  src/client/components/Products/Products.stories.js
  src/client/components/ProductsPageView/ProductsPageView.stories.js
  src/client/components/Sort/Sort.component.js
  src/client/containers/AboutUsPage/AboutUsPage.container.js
  src/client/containers/ContactUsPage/ContactUsPage.container.js
Labels: bug, Frontend

#155 Frontend-Footer-Link
  src/client/components/Footer/Footer.component.js
  src/server/migrations/20220215204621_create_orders_table.js
  src/server/migrations/20220215204708_create_order_items_table.js
Labels: Frontend

#102 FrontEnd: Recover Password Form
  src/client/components/RecoverPassword/RecoverPassword.js
  src/client/components/RecoverPassword/RecoverPassword.stories.js
  src/client/components/RecoverPassword/RecoverPassword.styles.css
Labels: Storybook, Frontend

#137 updated favorite list component css styling
  src/client/components/FavouriteList/FavouriteList.component.js
  src/client/components/FavouriteList/FavouriteList.styles.css
Labels: Frontend

#110 Backend API for adding/deleting favorites products
  src/server/api/controllers/favorites.controller.js
  src/server/api/routes/api-router.js
  src/server/api/routes/favorites.router.js
Labels: Backend

#143 Databases: Created seeding for order_items table
  src/server/seeds/development/04_order_items_table.js
Labels: Databases

#142 Databases: Created seeding for orders table
  src/server/seeds/development/03_orders_table.js
Labels: Databases

#135 Fix: sort component styles
  src/client/components/Sort/Sort.component.js
  src/client/components/Sort/Sort.styles.css
Labels: Frontend

#173 Backend: Seeds / More data to seed files #172
  src/server/migrations/20220215204621_create_orders_table.js
  src/server/seeds/development/03_orders_table.js
  src/server/seeds/development/04_order_items_table.js
Labels: Backend

#169 Forgot password page
  src/client/App.js
  src/client/components/Login/Login.component.js
  src/client/components/RecoverPassword/RecoverPassword.component.js
  src/client/components/RecoverPassword/RecoverPassword.styles.css
  src/client/containers/ForgotPasswordPage/ForgotPasswordPage.Container.js
  src/client/containers/ForgotPasswordPage/ForgotPasswordPage.container.js
Labels: Frontend

#146 seeding in favorite table
  src/server/seeds/development/05_favorites_table.js
Labels: Databases

#166 Backend: Endpoint products sorting
  src/server/api/controllers/products.controller.js
  src/server/api/routes/products.router.js
Labels: Backend

#176 Fix the user, product and order table
  src/server/migrations/20220129153235_create_users_table.js
  src/server/migrations/20220202135116_create_favorites_table.js
  src/server/migrations/20220215204621_create_orders_table.js
  src/server/migrations/20220215204708_create_order_items_table.js
  src/server/seeds/development/01_users_table.js
  src/server/seeds/development/02_products_table.js
  src/server/seeds/development/03_orders_table.js
  src/server/seeds/development/04_order_items_table.js
  src/server/seeds/development/05_favorites_table.js
Labels: Databases

#111 Feature/special offer products list
  src/client/components/SpecialOfferProductsList/OfferProductsList.js
  src/client/components/SpecialOfferProductsList/OfferProductsList.stories.js
  src/client/components/SpecialOfferProductsList/OfferProductsList.styles.css
  src/client/components/SpecialOffers/OfferProductModel.component.js
  src/client/components/SpecialOffers/OfferProductModel.styles.css
Labels: Storybook

#145 FrontEnd: 404 page container
  src/client/App.js
  src/client/assets/images/404.png
  src/client/containers/404Page/404Page.Container.js
  src/client/containers/404Page/404Page.styles.css
Labels: Frontend

#181 Backend: Add update User endpoint
  src/server/api/controllers/users.controller.js
  src/server/api/routes/users.router.js
Labels: Backend

#140 Fix: LoginForm #139
  src/client/App.js
  src/client/components/Login/Login.component.js
  src/client/components/Login/Login.styles.css
  src/client/containers/LogInPage/LogInPage.Container.js
  src/client/containers/LoginPage/LogInPage.styles.css
Labels: bug

#177 [Frontend] Update LandingPage pagination
  src/client/components/Pagination/Pagination.component.js
  src/client/components/Pagination/Pagination.styles.css
  src/client/components/Sort/Sort.component.js
  src/client/components/SpecialOfferBanner/SpecialOfferBanner.component.js
  src/client/containers/LandingPage/LandingPage.container.js
  src/client/containers/LandingPage/LandingPage.styles.css
  src/client/hooks/useProducts.js
  src/server/api/controllers/products.controller.js
Labels: Frontend

#174 [Backend] Add GET /orders/:id endpoint
  src/server/api/controllers/orders.controller.js
  src/server/api/routes/api-router.js
  src/server/api/routes/orders.router.js
Labels: Backend

#189 Frontend-Fixing-About and Contact page
  src/client/containers/AboutUsPage/AboutUsPage.container.js
  src/client/containers/ContactUsPage/ContactUsPage.container.js
Labels: Frontend

#112 Add GET /user/:id endpoint
  src/server/api/controllers/users.controller.js
  src/server/api/routes/api-router.js
  src/server/api/routes/users.router.js
Labels: Backend

#183 Fix offer products list new
  src/client/components/OfferProductsList/OfferProductsList.component.js
  src/client/components/OfferProductsList/OfferProductsList.stories.js
  src/client/components/OfferProductsList/OfferProductsList.styles.css
  src/client/components/SpecialOffers/OfferProductModel.styles.css
Labels: Storybook, Frontend

#161 Frontend-SpecialofferPage-container
  src/client/App.js
  src/client/components/OfferProductsList/OfferProductsList.styles.css
  src/client/components/SpecialOfferBanner/SpecialOfferBanner.component.js
  src/client/components/SpecialOffers/OfferProductModel.component.js
  src/client/components/SpecialOffers/OfferProductModel.styles.css
  src/client/containers/SpecialOfferPage/SpecialOfferPage.Container.js
  src/client/containers/SpecialOfferPage/SpecialOfferPage.container.js
  src/client/containers/SpecialOfferPage/SpecialOfferPage.styles.css
Labels: Frontend

#184 fix:^button css
  src/client/components/Button/Button.styles.css
Labels: Frontend
