Repository HackYourFuture-CPH/fp-class19, pull requests merged in 2022-01, with the labels that each got.

#19 Databases: Create Products table ( Migrations + Seeds ) #18
  src/server/knexfile.js
  src/server/migrations/20220123184131_create_products_table.js
  src/server/seeds/development/01_products_table.js
Labels: Databases

#45 Frontend: About Us
  src/client/assets/fonts/DancingScript-Bold.ttf
  src/client/assets/fonts/DancingScript-Medium.ttf
  src/client/assets/fonts/DancingScript-Regular.ttf
  src/client/assets/fonts/DancingScript-SemiBold.ttf
  src/client/assets/fonts/DancingScript-VariableFont_wght.ttf
  src/client/assets/fonts/Inter-Black.ttf
  src/client/assets/fonts/Inter-Bold.ttf
  src/client/assets/fonts/Inter-ExtraBold.ttf
  src/client/assets/fonts/Inter-ExtraLight.ttf
  src/client/assets/fonts/Inter-Light.ttf
  src/client/assets/fonts/Inter-Medium.ttf
  src/client/assets/fonts/Inter-Regular.ttf
  src/client/assets/fonts/Inter-SemiBold.ttf
  src/client/assets/fonts/Inter-Thin.ttf
  src/client/assets/fonts/Inter-VariableFont_slnt,wght.ttf
  src/client/assets/fonts/Roboto-Black.ttf
  src/client/assets/fonts/Roboto-BlackItalic.ttf
  src/client/assets/fonts/Roboto-Bold.ttf
  src/client/assets/fonts/Roboto-BoldItalic.ttf
  src/client/assets/fonts/Roboto-Italic.ttf
  src/client/assets/fonts/Roboto-Light.ttf
  src/client/assets/fonts/Roboto-LightItalic.ttf
  src/client/assets/fonts/Roboto-Medium.ttf
  src/client/assets/fonts/Roboto-MediumItalic.ttf
  src/client/assets/fonts/Roboto-Regular.ttf
  src/client/assets/fonts/Roboto-Thin.ttf
  src/client/assets/fonts/Roboto-ThinItalic.ttf
  src/client/assets/images/image26.png
  src/client/components/AboutUs/aboutus.component.js
  src/client/components/AboutUs/aboutus.style.css
  src/client/index.css
Labels: Frontend

#48 Databases: Create Users table ( Migrations + Seeds ) #25
  src/server/migrations/20220129153235_create_users_table.js
  src/server/seeds/development/01_users_table.js
Labels: Databases

#29 Add migrations for favorites #28
  src/server/migrations/20220125195742_create_favorites_table.js
Labels: Databases

#41 Frontend menu component#5
  src/client/App.js
  src/client/components/Menu/Menu.js
  src/client/components/Menu/MenuItem.js
  src/client/components/Menu/menu.css
Labels: Frontend

#23 Frontend: Footer Component #7
  src/client/App.js
  src/client/assets/images/emailsend.png
  src/client/assets/images/logo.png
  src/client/components/Footer/Footer.css
  src/client/components/Footer/Footer.js
  src/client/components/SpecialOfferBanner/Specialoffer.js
Labels: Frontend

#42 Storybook: Header component
  src/client/App.js
  src/client/assets/images/favorite-icon.png
  src/client/assets/images/logo.png
  src/client/assets/images/shopping-cart.png
  src/client/assets/images/user-login.png
  src/client/components/Header/Header.css
  src/client/components/Header/Header.js
  src/client/components/Header/Header.stories.js
  src/client/components/Navigation/Header.js
  src/server/migrations/20220125195742_create_favorites_table.js
Labels: Storybook

#20 Frontend: Product sorting
  src/client/components/SortComponent/SortComponent.js
  src/client/components/SortComponent/SortComponent.stories.js
  src/client/components/SortComponent/SortComponent.styles.css
Labels: Storybook, Frontend

#38 adding button componant and nvmrc file
  .nvmrc
  src/client/components/Button/Button.css
  src/client/components/Button/Button.js
  src/client/components/Button/Button.stories.js
Labels: Storybook

#55 Frontend: Special Offer Banner Component
  src/client/assets/images/specialofferbanner.png
  src/client/assets/images/specialoffertopbanner.png
  src/client/components/SpecialOfferBanner/Specialoffer.css
  src/client/containers/Home/Home.js
Labels: Frontend

#30 FrontEnd: Login Form
  __mocks__/fileMock.js
  __mocks__/styleMock.js
  src/client/App.js
  src/client/assets/images/goog.png
  src/client/assets/images/logo1.png
  src/client/components/LoginComponent/LoginComponent.js
  src/client/components/LoginComponent/LoginComponent.stories.js
  src/client/components/LoginComponent/LoginComponent.styles.css
  src/client/containers/Home/Home.js
Labels: Storybook, Ready for development, Frontend
